name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.0+17
  firebase_storage: ^4.0.1
  audioplayers: ^0.10.0
  intl: ^0.16.1
  extended_text_field: 3.0.1
  fluttertoast: ^7.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - assets/
